control_configurations:
  - name: watch
    components:
      - {hardware_interface: "ur_hw", controller : "js_pub"}
      - {hardware_interface: "ft_hw", controller : "ft_pub", runtime_check: false}

  - name: ctrl
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "p_j"}
      
  - name: zz_cart_impedance
    depends: [watch]
    components:
      - {hardware_interface: "ur_hw", controller : "c_pose_pub"}
      - { hardware_interface: "ur_hw", controller : "cart_impedance_controller"}
      
  - name: zz_joint_impedance
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "joint_impedance_controller"}

  - name: zz_jjog
    depends: [ watch ]
    components:
      - {hardware_interface: "ur_hw", controller: "jjog"}

  - name: zz_cjog
    depends: [ watch ]
    components:
      - {hardware_interface: "ur_hw", controller: "c_vel"}

  - name: simple_touch
    depends: [ zz_cjog ]
    components:
      - {hardware_interface: "ft_hw", controller: "simple_touch"}

  - name: simple_touch_impedance
    depends: [ zz_cart_impedance ]
    components:
    - {hardware_interface: "ft_hw", controller: "simple_touch"}
    - {hardware_interface: "plan_hw", controller: "c_vel"}


#  - name: cart_vel_impedance
#    depends: [ zz_cart_impedance ]
#    components:
#    - {hardware_interface: "plan_hw", controller: "c_vel"}

  - name: gt
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "gt"}

  - name: lqr
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "lqr"}

  - name: imp_low_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_low_k"}

  - name: imp_high_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_high_k"}

  - name: imp_var_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_var_k"}


  - name: thor
    depends: [ ctrl ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: thor_cimp
    depends: [ zz_cart_impedance ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: thor_jimp
    depends: [ zz_joint_impedance ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}

configuration_dispatches:
- { name: watch,  at: 1.0 }
- { name: thor ,  at: 2.0 }

