control_configurations:
  - name: watch
    components:
      - {hardware_interface: "ur_hw", controller : "js_pub"}
      - {hardware_interface: "ft_hw", controller : "ft_pub",  runtime_check: false}

  - name: ctrl
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "p_j"}
      
  - name: cart_impedance
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "cart_impedance_controller", runtime_check: false}
      
  - name: joint_impedance
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "joint_impedance_controller", runtime_check: false}

  - name: jjog
    depends: [ watch ]
    components:
      - {hardware_interface: "ur_hw", controller: "jjog"}

  - name: cjog
    depends: [ watch ]
    components:
      - {hardware_interface: "ur_hw", controller: "c_vel"}

  - name: simple_touch
    depends: [ cjog ]
    components:
      - {hardware_interface: "ft_hw", controller: "simple_touch", runtime_check: false}


  - name: simple_touch_impedance
    depends: [ cart_impedance ]
    components:
    - {hardware_interface: "ft_hw", controller: "simple_touch", runtime_check: false}
    - {hardware_interface: "plan_hw", controller: "c_vel", runtime_check: false}

  - name: gt
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "gt"}

  - name: var_imp
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "var_imp"}

  - name: thor
    depends: [ ctrl ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: thor_cimp
    depends: [ cart_impedance ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: thor_jimp
    depends: [ joint_impedance ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}

configuration_dispatches:
- { name: watch,  at: 1.0 }
- { name: thor ,  at: 2.0 }

