control_configurations:
  - name: watch
    components:
      - {hardware_interface: "ur_hw", controller : "js_pub"}
      #- {hardware_interface: "ft_hw", controller : "ft_pub", runtime_check: false}

  - name: gt
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "gt"}

  - name: lqr
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "lqr"}

  - name: imp_low_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_low_k"}

  - name: imp_high_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_high_k"}

  - name: imp_var_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_var_k"}

  - name: imp_NO_k
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "imp_NO_k"}

  - name: non_coop_IOC
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "non_coop_ioc"}

  - name: LQR_impedance
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "LQR_impedance"}

  - name: freq_est
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "freq_est"}

  - name: ctrl
    depends: [watch]
    components:
      - { hardware_interface: "ur_hw", controller : "p_j"}

  - name: planner
    depends: [ ctrl ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}

configuration_dispatches:
  - { name: watch,  at: 1.0 }
  - { name: planner,  at: 2.0 }

