control_configurations:    
  - name: watch
    components:
      - {hardware_interface: "ur_hw", controller : "js_pub"}
      - {hardware_interface: "ft_hw", controller : "ft_pub", runtime_check: false}
      
  - name: gt_traj_arb
    depends: [ watch ]
    components:
      - {hardware_interface: "ur_hw", controller: "gt_traj_arb"}
      #- {hardware_interface: "ur_hw", controller: "p_j"}
      #- {hardware_interface: "plan_hw", controller: "gt_traj_arb"}

  - name: drapebot_integration
    depends: [ watch ]
    components:
    - {hardware_interface: "ur_hw", controller: "drapebot_integration"}
    
    
  - name: dist_mpc
    depends: [ watch ]
    components:
    #- {hardware_interface: "ur_hw", controller: "dist_mpc"}
      - {hardware_interface: "ur_hw", controller: "p_j"}
      - {hardware_interface: "plan_hw", controller: "dist_mpc"}
    
    
  - name: ctrl
    depends: [watch]
    hidden: true
    components:
      - { hardware_interface: "ur_hw", controller : "p_j"}

  - name: planner
    depends: [ ctrl ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
    
  - name: arbitration_planner
    depends: [ gt_traj_arb ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}
      
  - name: drapebot_arbitration_planner
    depends: [ drapebot_integration]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}


    
    
    
  - name: fake_watch
    components:
      - {hardware_interface: "fake_hw", controller : "js_pub"}
      
  - name: fake_ctrl
    depends: [fake_watch]
    hidden: true
    components:
      - { hardware_interface: "fake_hw", controller : "p_j"}

  - name: fake_planner
    depends: [ fake_ctrl ]
    components:
    - {hardware_interface: "plan_hw", controller: "microint"}

  - name: fake_gt_traj_arb
    depends: [ fake_watch ]
    components:
    - {hardware_interface: "fake_hw", controller: "gt_traj_arb"}
    
    
configuration_dispatches:
  - { name: watch,  at: 1.0 }
  - { name: planner,  at: 2.0 }
  
  #- { name: fake_watch,  at: 1.0 }
  #- { name: fake_planner,  at: 2.0 }
  
