ur_hw:
  type: cnr_ur_driver/UrCB3HardwareInterface
#  type: ur_driver/HardwareInterface
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "ur_hw"
  default_throttle_time: 20.0
  sampling_period: 0.008
  joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  joints:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

  robot_ip: 192.168.254.30
  reverse_port: 50001
  script_sender_port: 50002
  tf_prefix: ''
  headless_mode: false
  script_file:        /home/marie/cnr_ws/src/devices/robots/ur/Universal_Robots_ROS_Driver/ur_robot_driver/resources/ros_control.urscript
  output_recipe_file: /home/marie/cnr_ws/src/devices/robots/ur/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_output_recipe.txt
  input_recipe_file:  /home/marie/cnr_ws/src/devices/robots/ur/Universal_Robots_ROS_Driver/ur_robot_driver/resources/rtde_input_recipe.txt
  ext_control_path: /programs/exc.urp
  use_tool_communication: false
  tool_voltage: 0
  tool_parity: 0
  tool_baud_rate: 115200
  tool_stop_bits: 1
  tool_rx_idle_chars: 1.5
  tool_tx_idle_chars: 3.5

  base_link  : "base_link"
  tool_link  : "tool0"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  remap_source_args:
  - "/ur_hw/js_pub/joint_states"
  - "/ur_hw/gt/current_pose"
  - "/ur_hw/gt/alpha"
  - "/ur_hw/gt/filtered_wrench_base"
  - "/ur_hw/gt/wrench_base"
  - "/ur_hw/gt/var_D"
  - "/ur_hw/gt/var_K"
  - "/ur_hw/gt/robot_u"
  - "/ur_hw/gt/human_u"
  - "/ur_hw/gt/human_wrench"
  - "/ur_hw/lqr/current_pose"
  - "/ur_hw/lqr/alpha"
  - "/ur_hw/lqr/filtered_wrench_base"
  - "/ur_hw/lqr/wrench_base"
  - "/ur_hw/lqr/var_D"
  - "/ur_hw/lqr/var_K"
  - "/ur_hw/lqr/robot_u"
  - "/ur_hw/lqr/human_u"
  - "/ur_hw/lqr/human_wrench"
  - "/ur_hw/imp_low_k/current_pose"
  - "/ur_hw/imp_low_k/filtered_wrench_base"
  - "/ur_hw/imp_low_k/wrench_base"
  - "/ur_hw/imp_low_k/var_D"
  - "/ur_hw/imp_low_k/var_K"
  - "/ur_hw/imp_low_k/human_wrench"
  - "/ur_hw/imp_high_k/current_pose"
  - "/ur_hw/imp_high_k/filtered_wrench_base"
  - "/ur_hw/imp_high_k/wrench_base"
  - "/ur_hw/imp_high_k/var_D"
  - "/ur_hw/imp_high_k/var_K"
  - "/ur_hw/imp_high_k/human_wrench"
  - "/ur_hw/imp_var_k/current_pose"
  - "/ur_hw/imp_var_k/filtered_wrench_base"
  - "/ur_hw/imp_var_k/wrench_base"
  - "/ur_hw/imp_var_k/var_D"
  - "/ur_hw/imp_var_k/var_K"
  - "/ur_hw/imp_var_k/human_wrench"
  - "/ur_hw/imp_var_k/alpha"
  - "/ur_hw/non_coop_ioc/current_pose"
  - "/ur_hw/LQR_impedance/current_pose"
  - "/ur_hw/imp_NO_k/current_pose"
  - "/ur_hw/imp_NO_k/filtered_wrench_base"
  - "/ur_hw/imp_NO_k/wrench_base"
  - "/ur_hw/imp_NO_k/var_D"
  - "/ur_hw/imp_NO_k/var_K"
  - "/ur_hw/imp_NO_k/human_wrench"
  - "/ur_hw/imp_NO_k/alpha"
  - "/ur_hw/imp_NO_k/stamp_wrench"

  remap_target_args:
  - "/joint_states"
  - "/current_pose"
  - "/alpha"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/robot_u"
  - "/human_u"
  - "/human_wrench"
  - "/current_pose"
  - "/alpha"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/robot_u"
  - "/human_u"
  - "/human_wrench"
  - "/current_pose"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/human_wrench"
  - "/current_pose"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/human_wrench"
  - "/current_pose"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/human_wrench"
  - "/alpha"
  - "/current_pose"
  - "/current_pose"
  - "/current_pose"
  - "/filtered_wrench_base"
  - "/wrench_base"
  - "/var_D"
  - "/var_K"
  - "/human_wrench"
  - "/alpha"
  - "/stamp_wrench"

  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joints: all

  c_pose_pub:
    type: cnr/control/StateCtrl
    controlled_joints: all
    kin_update_period: 0.008
    cartesian_pose_topic: "current_pose"

  tf_pub:
    type: cnr/control/RobotStateController
    controlled_joints: all
    frames: ["ur5_tool0"]

  jjog:
    type: "cnr/control/JointTeleopController"
    controlled_joints: all

  p_j:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /joint_pos_target
    controlled_joints: all
    kin_update_period : 0.008

  gt:
    type: cnr/control/GtTrajDeformation
    controlled_joints: all
    kin_update_period: 0.008

#    Q_hat: [50, 50, 50, 1, 1, 1]
#    R_hat: [1 ,  1,  1, 0, 0, 0]
#    Qr   : [20, 20, 20, 1, 1, 1]     #OK
#    Rr   : [ 0,  0,  0, .5, .5, .5]  #OK
    Q_hat: [50, 50, 50, 1, 1, 1]
    R_hat: [10 ,  10,  10, 0, 0, 0]
    Qr   : [20, 20, 20, 1, 1, 1]
    Rr   : [ 1,  1,  1, .01, .01, .1]


    M_r: [10,10,6,1,1,1]
    K_r: [0,0,6,0,0,0]
    D_r: [40,40,1.5,1,1,1]
#    D_r: [60,60,1.5,1,1,1]
    damping_is_ratio: false

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,1,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"

    sigmoid_width: 0.7
    sigmoid_half_x: 7
    sigmoid_height: 0.98     # for shared control (variable impedance)
    sigmoid_max_y: 0.99

    exponential: 0.5 # exponential method to vary alpha

  lqr:
    type: cnr/control/GtTrajDeformation
    controlled_joints: all
    exponential: 4
    min_val: 29
    kin_update_period: 0.008

    Q_hat: [50, 50, 50, 1, 1, 1]
    R_hat: [10 ,  10,  10, 0, 0, 0]
    Qr   : [20, 20, 20, 1, 1, 1]
    Rr   : [ 1,  1,  1, .1, .1, .1]

#    Q_hat: [50, 50, 50, 1, 1, 1]
#    R_hat: [1 ,  1,  1, 0, 0, 0]
#    Qr   : [20, 20, 20, 1, 1, 1]
#    Rr   : [ .1,  .1,  .1, .1, .1, .1]

    M_r: [10,10,6,1,1,1]
    K_r: [0,0,6,0,0,0]
#    D_r: [1,1,1.5,1,1,1]
    D_r: [40,40,1.5,1,1,1]
    damping_is_ratio: false

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,1,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"

    sigmoid_width: 3
    sigmoid_half_x: 2
    sigmoid_height: 0        # for robot control  (fixed impedance)
    sigmoid_max_y: 0.99

  imp_low_k:
    type: cnr/control/VariableImpedanceCtrl
    controlled_joints: all
    kin_update_period: 0.008


    M_r: [10,10,10,1,1,1]
    K_r: [20,20,6,0,0,0]
    D_r: [0.9,0.9,1.5,1,1,1]
    damping_is_ratio: true

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,1,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"
    #twist_target: "/target_cart_twist"

    use_sigmoid: false
    exponential: 0
    min_val: 0


  imp_var_k:
    type: cnr/control/VariableImpedanceCtrl
    controlled_joints: all
    variable_damping: false
    kin_update_period: 0.008


    M_r: [10,10,6,1,1,1]
    K_r: [550,550,6,0,0,0]
#    D_r: [1.2,1.2,1.5,1,1,1]
    D_r: [0.9,0.9,1.5,1,1,1]
    damping_is_ratio: true

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,3,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"

    use_sigmoid: false

    sigmoid_width: 0.1
    sigmoid_half_x: 10
    sigmoid_height: 0.98     # for shared control (variable impedance)
    sigmoid_max_y: 0.99

    exponential: .5
    min_val: 45

  imp_high_k:
    type: cnr/control/VariableImpedanceCtrl
    controlled_joints: all
    kin_update_period: 0.008

    M_r: [10,10,6,1,1,1]
    K_r: [100,100,6,0,0,0]
    D_r: [0.9,0.9,1.5,1,1,1]
    damping_is_ratio: true

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,3,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"

    use_sigmoid: false
    exponential: 0
    min_val: 0


  imp_NO_k:
    type: cnr/control/VariableImpedanceCtrl
    controlled_joints: all
    kin_update_period: 0.008

    M_r: [10,100,6,1,1,1]
    K_r: [0,1000,0,0,0,0]
    D_r: [100,2500,25,1,1,1]
    damping_is_ratio: false

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,3,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true
    external_wrench_topic: "/robotiq_ft_wrench"

    pose_target: "/target_cart_pose"

    use_sigmoid: false
    exponential: 0
    min_val: 0

  non_coop_ioc:
    type: cnr/control/NonCooperativeGt
    controlled_joints: all
    kin_update_period: 0.008

    external_wrench_topic: "/robotiq_ft_wrench"
    pose_target: "/target_cart_pose"

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,1,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true

    Q_hat: [1, 1]
    R_hat: [1]
    Qr   : [2, 2]
    Rr   : [1]

    M_r: [10,10,6,1,1,1]
    K_r: [110,110,6,0,0,0]
    D_r: [40,40,1.5,1,1,1]
    damping_is_ratio: false

    window: 125


  LQR_impedance:
    type: cnr/control/LQRImpedance
    controlled_joints: all
    kin_update_period: 0.008

    external_wrench_topic: "/robotiq_ft_wrench"
    pose_target: "/target_cart_pose"

    robot_base_frame  : ur5_base_link
    robot_tip_frame   : ur5_tool0
    force_sensor_frame: robotiq_ft_frame_id

    wrench_deadband: [1,1,1,5,5,5]
    omega_wrench: 500
    use_filtered_wrench: true

    Q: [10, 1]
    R: [.1]

    M_r: [10,10,6,1,1,1]
    K_r: [0,110,6,0,0,0]
    D_r: [50,40,1.5,1,1,1]
    damping_is_ratio: false

    window: 125



  freq_est:
    type: cnr/control/MultisineIdentificationController
    controlled_joints: all
    base_link  : "base_link"
    tool_link  : "tool0"
    kin_update_period: 0.008
    appenders: [file, screen]
    levels: [trace, info]
    pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
    file_name: "freq_est"
    active_joint: "wrist_1_joint"

    # multisine parameters:
    rampup_time: 10.0  # [seconds] transient time before and after the multisine signal.

    carrier:
      angular_frequency: 0.5       # [rad/s]            angular frequency
      amplitude: 0.1               # [rad or m]         amplitude of the carrier
      periods:   2.0               # [-]                number of repetitions of the carrier (round using std::ceil)

    input:
      max_pos: 0.05                # [rad     or m]     maximum amplitude of the signal in position (deflection from the starting point)
      max_vel: 1.0                 # [rad/s   or m/s]   maximum velocity of the signal
      max_acc: 3.0                 # [rad/s^2 or m/s^2] maximum acceleration of the signal

      min_angular_frequency: 1.0   # [rad/s]            must be high than carrier/angular_frequency
      max_angular_frequency: 100.0 # [rad/s]            must be high than input/min_angular_frequency
      harmonics_number: 10         # [-]                number of harmonics in the multisine signal

